### ISSUE TITLE
[FEATURE] Font Selection

### ISSUE THREAD

**Issue by Justinzobel** [solus-cold-storage/journal#43]
Need font selection.

**Comment by ryanleesipes** [comment]
Using monospace, will look into more options in regards to font selection.

**Comment by Justinzobel** [comment]
Monospace is good, other monospace options might suit each user differently
:)

**Comment by ryanleesipes** [comment]
Will have to look into this more, as I'm not a monospace expert. What other monospace options are there?

**Comment by Justinzobel** [comment]
Not so much just monospace but options for any font on the system. Others
might have a custom monospace that they want so a list of fixed options
isn't worthwhile, just a standard font chooser like most text editors have.
