### ISSUE TITLE
[FEATURE] Find/Find&Replace

### ISSUE THREAD

**Issue by Justinzobel** [solus-cold-storage/journal#49]
Ctrl F / Ctrl H are pretty standard shortcuts for them :D
##

**Comment by michaelrutherford** [comment]
The search/find functionality was added in the last commit.

**Comment by michaelrutherford** [comment]
I'm currently working on the keyboard shortcuts and replace functions..

**Comment by ryanleesipes** [comment]
:) awesome.

**Comment by Justinzobel** [comment]
Closing due to journal no longer in development.
