### ISSUE TITLE
Ctrl S doesn't work with multiple tabs open

### ISSUE THREAD

**Issue by Justinzobel** [solus-cold-storage/journal#54]
As per the title
##

**Comment by ryanleesipes** [comment]
It appears to work with multiple tabs on mine, but the original window doesn't work when I drag a tab out of the notebook to generate a new window. Can you confirm this behavior is happening to you when you only have one Journal window?

**Comment by ryanleesipes** [comment]
@Justinzobel can you verify whether or not you had multiple windows open at the time?

**Comment by Justinzobel** [comment]
Sorry not sure, I'll note down more details next time it happens.

**Comment by ryanleesipes** [comment]
I ran into this issue, appears to be when there are multiple windows, Ctrl+S no longer works with the old window at that point.

**Comment by Justinzobel** [comment]
Oh cool, at least it's reproducible, sorry I didn't get back to you with more info.

**Comment by michaelrutherford** [comment]
I'll start working on a fix as soon as I can.

**Comment by Justinzobel** [comment]
Closing due to journal no longer in development.
