### ISSUE TITLE
Swap Ctrl N and Ctrl T

### ISSUE THREAD

**Issue by Justinzobel** [solus-cold-storage/journal#67]
Ctrl N imho should be new Window
Ctrl T should be new Tab
##

**Comment by michaelrutherford** [comment]
I actually almost implemented this in my last commit, but I didn't know if anybody else would want that. I'll go ahead and start working on it.

**Comment by Justinzobel** [comment]
Heh I demand far too many features :D

**Comment by ryanleesipes** [comment]
Yarb.

**Comment by michaelrutherford** [comment]
The CTRL+T shortcut was added in the last update. I'm currently working on CTRL+N.

**Comment by Justinzobel** [comment]
Closing due to journal no longer in development.
